const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {today,almanac,parse,split}=require('./core.cjs');
const {analyze,config,loadState,saveState,createHandler}=require('./server.cjs');
test('北京时间及有效日期',()=>{assert.equal(today(new Date('2026-10-08T16:01Z')),'2026-10-09');assert.equal(almanac('2024-02-29').date,'2024-02-29');for(const d of ['2025-02-29','2026-13-01','2026-02-30','0001-01-01'])assert.throws(()=>almanac(d));});
test('已知春节及宜忌',()=>{assert.match(almanac('2024-02-10').lunar,/正月初一/);assert.deepEqual(almanac('2026-10-09').yi,['祭祀','解除','破屋','坏垣','馀事勿取']);});
test('命令及错误输入',()=>{assert.equal(parse('/date@mybot 2026-10-09').date,'2026-10-09');assert.equal(parse('/ask 2026-10-09 宜忌').question,'宜忌');assert.throws(()=>parse('/ask 2026-02-30 宜忌'));assert.throws(()=>parse('x'.repeat(801)));});
test('消息分段不截断emoji',()=>{const s='😀'.repeat(3000),chunks=split(s);assert.equal(chunks.join(''),s);assert.ok(chunks.every(x=>x.length<=3500));});
test('持久化与损坏校验',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'almanac-'));try{const file=path.join(dir,'state.json');assert.equal(loadState(file).offset,0);saveState(file,{offset:9,day:'2026-10-09',used:2});assert.equal(loadState(file).used,2);fs.writeFileSync(file,'{}');assert.throws(()=>loadState(file));}finally{fs.rmSync(dir,{recursive:true});}});
test('DeepSeek请求和空响应',async()=>{const a=almanac('2026-10-09'),c={key:'test',model:'test-model'};assert.equal(await analyze(c,a,'解释',async(url,b,h)=>{assert.equal(url,'https://api.deepseek.com/chat/completions');assert.equal(JSON.parse(b.messages[1].content).calendar.date,a.date);assert.equal(h.Authorization,'Bearer test');return {choices:[{message:{content:'解读'}}]};}),'解读');await assert.rejects(()=>analyze(c,a,'解释',async()=>({choices:[]})));});
function setup(ai=async()=> '解释'){const sent=[],state={offset:0,day:'',used:0};let saves=0,now=new Date('2026-10-09T01:00Z');const handler=createHandler({allowed:new Set(['123']),key:'test',daily:1},state,()=>saves++,async(m,b)=>sent.push(b.text),ai,()=>now);const msg=(text,id=123,type='private')=>({message:{chat:{id,type},from:{id},text}});return {sent,state,handler,msg,get saves(){return saves},advance(){now=new Date(now.getTime()+20000)}};}
test('授权及私聊边界',async()=>{const x=setup();await x.handler(x.msg('/ask 解读',999));assert.match(x.sent[0],/未授权/);await x.handler(x.msg('/id',999));assert.match(x.sent[1],/999/);await x.handler(x.msg('/ask 解读',123,'group'));assert.equal(x.sent.length,2);assert.equal(x.state.used,0);});
test('免费查询、冷却及持久化额度',async()=>{let calls=0;const x=setup(async()=>{calls++;return '解读'});await x.handler(x.msg('/today'));assert.equal(calls,0);await x.handler(x.msg('/ask 解读'));assert.equal(calls,1);assert.equal(x.saves,1);await x.handler(x.msg('/ask 解读'));assert.match(x.sent.at(-1),/15秒/);x.advance();await x.handler(x.msg('/ask 解读'));assert.match(x.sent.at(-1),/额度/);assert.equal(calls,1);});
test('AI故障保留本地黄历',async()=>{const x=setup(async()=>{throw Error('secret')});await x.handler(x.msg('/ask 解读'));assert.match(x.sent[0],/2026-10-09/);assert.match(x.sent[1],/暂时无法/);assert.ok(!x.sent.join('').includes('secret'));});
test('缺失令牌、空白名单及坏配置',()=>{assert.equal(config({TELEGRAM_BOT_TOKEN:'test'}).allowed.size,0);assert.throws(()=>config({}));assert.throws(()=>config({TELEGRAM_BOT_TOKEN:'test',MAX_DAILY_AI_REQUESTS:'NaN'}));});

test('命令模板可复制，日期和解读菜单无参数时给模板',async()=>{for(const t of ['/template','命令模板','/date','/ask'])assert.equal(parse(t).kind,'template');assert.equal(parse('今天黄历').kind,'date');let result;const h=createHandler({allowed:new Set(['123'])},{},()=>{},async(m,b)=>{result=b},undefined,()=>new Date('2026-10-09T00:00Z'));await h({message:{chat:{id:123,type:'private'},from:{id:123},text:'/template'}});assert.equal(result.reply_markup.inline_keyboard[1][0].copy_text.text,'/date 2026-10-09');assert.match(result.reply_markup.inline_keyboard[2][0].copy_text.text,/^\/ask 2026-10-09/);});
